import type { LucideIcon } from 'lucide-react';
import {
  BarChart3,
  BookOpen,
  Brain,
  Building2,
  Church,
  Compass,
  Cpu,
  FlaskConical,
  Gavel,
  Globe2,
  Landmark,
  Leaf,
  Map,
  Megaphone,
  MessageSquare,
  Scale,
  Shield,
  Sparkles,
  Users,
  Vote,
  Wand2,
  Building,
  History,
  Lightbulb,
  Network,
} from 'lucide-react';

const temaIcons: Record<string, LucideIcon> = {
  inicio: Sparkles,
  filosofia: BookOpen,
  'teoria-del-estado': Landmark,
  'gobierno-y-estructura-politica': Building2,
  'ideologias-politicas': Wand2,
  'democracia-y-elecciones': Vote,
  'relaciones-internacionales-y-geopolitica': Globe2,
  economia: Landmark,
  'derecho-y-constitucion': Gavel,
  'sociologia-politica': Users,
  historia: History,
  'seguridad-y-defensa': Shield,
  'politicas-publicas': Lightbulb,
  'comunicacion-politica': Megaphone,
  'etica-politica': Scale,
  'tecnologia-y-politica': Cpu,
  'medio-ambiente-y-recursos': Leaf,
  'psicologia-politica': Brain,
  'corrientes-y-modelos-modernos': Network,
  'religion-y-politica': Church,
  'cultura-politica': MessageSquare,
  'politica-y-ciencia': FlaskConical,
  'politica-urbana': Building,
  'poder-y-control-social': Shield,
  'estadisticas-mundiales': BarChart3,
  'globo-teraqueo-politico': Map,
};

export function getTemaIcon(temaId: string): LucideIcon {
  return temaIcons[temaId] ?? Compass;
}
